DROP TABLE IF EXISTS dog CASCADE;
CREATE TABLE dog
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    sex CHAR(1),
    age INT,
    breed VARCHAR(255),
    weight FLOAT,
    location VARCHAR(255),
    photo VARCHAR(255),
    PRIMARY KEY (id)
);